id: PEF95150C
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS68018
  title: ཞལ་གདམས་དང་མགུར་གླུ་གཅེས་བཏུས།
  volumes:
    7272bdc1f04146838cb3585e76a8ec35:
      image_group_id: I8LS68020
      title: ''
      base_file: v001.txt
  author: ''
